spring:
  jpa:
    database-platform: com.trickyjava.bruno.quote.support.SQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:sqlite:sqlitesample.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin
    initialization-mode: always
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 5
      autoCommit: true
  security:
    user:
      name: client
      password: client
  boot:
    admin:
      client:
        url: http://localhost:9999
        username: admin
        password: admin
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always