spring:
  jpa:
    database-platform: com.trickyjava.bruno.quote.support.SQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:sqlite:sqlitesample.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin
    initialization-mode: always
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 5
      autoCommit: true